# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('advertisedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
